### ISSUE TITLE
Add support for GCP platform

### ISSUE THREAD

**Issue by sasikeda** [IBM/ibm-spectrum-scale-cloud-install#91]
Tasks list;

- [x] VPC template (1 public, 1 private subnet, bastion firewall, internal firewall)
- [x] Bastion template (1 external ip, 1 instance)
- [x] Compute nodes (Single, Mutli-AZ support, zero attached disks)
- [x] Compute desc node (1 attached disk, 1 instance in the zone specified)
- [ ] Support compute nodes expansion and contraction
- [x] Storage nodes (Single, Mutli-AZ support, zero attached disks)
- [x] Create specified number of attached disks (per zone)
- [x] Attach disks to storage nodes
- [x] metadata script for password less setup between nodes
- [x] NAT instance for internal nodes
- [x] gcs terraform backend
- [x] Readme updates
